# Generated by Django 4.0.5 on 2022-06-23 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vintage', models.PositiveIntegerField()),
                ('wine_producer', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=20)),
                ('wine_name', models.CharField(max_length=100)),
                ('grapes', models.TextField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('price', models.PositiveIntegerField(null=True)),
                ('img', models.CharField(max_length=1000)),
                ('active', models.BooleanField(default=True)),
                ('category', models.ManyToManyField(blank=True, to='product.category')),
            ],
        ),
    ]
