# Generated by Django 4.0.5 on 2022-06-24 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_wine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='country',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='wine',
            name='img',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='wine',
            name='vintage',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='wine',
            name='wine_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='wine',
            name='wine_producer',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
